#ifndef MIKUMIKUWORLD_VERSION_H
#define MIKUMIKUWORLD_VERSION_H

#define MMW_APP_VERSION_MAJOR 1
#define MMW_APP_VERSION_MINOR 1
#define MMW_APP_VERSION_PATCH 0
#define MMW_APP_VERSION_BUILD 0

#define MMW_APP_VERSION_NUMERIC 1,1,0,0
#define MMW_APP_VERSION_STRING "1.1.0.0"

#endif
