#ifndef MIKUMIKUWORLD_VERSION_H
#define MIKUMIKUWORLD_VERSION_H

#define MMW_APP_VERSION_MAJOR 1
#define MMW_APP_VERSION_MINOR 2
#define MMW_APP_VERSION_PATCH 1
#define MMW_APP_VERSION_BUILD 0

#define MMW_VERSION_STRINGIFY_IMPL(value) #value
#define MMW_VERSION_STRINGIFY(value) MMW_VERSION_STRINGIFY_IMPL(value)

#define MMW_APP_VERSION_STRING                                                                  \
	MMW_VERSION_STRINGIFY(MMW_APP_VERSION_MAJOR) "." MMW_VERSION_STRINGIFY(                    \
	    MMW_APP_VERSION_MINOR) "." MMW_VERSION_STRINGIFY(MMW_APP_VERSION_PATCH)
#define MMW_APP_VERSION_WINDOWS_STRING                                                          \
	MMW_APP_VERSION_STRING "." MMW_VERSION_STRINGIFY(MMW_APP_VERSION_BUILD)
#define MMW_APP_VERSION_GITHUB_TAG "v" MMW_APP_VERSION_STRING

#define MMW_APP_VERSION_NUMERIC                                                                 \
	MMW_APP_VERSION_MAJOR, MMW_APP_VERSION_MINOR, MMW_APP_VERSION_PATCH,                       \
	    MMW_APP_VERSION_BUILD
#define MMW_APP_VERSION_WINDOWS_NUMERIC MMW_APP_VERSION_NUMERIC

#endif
